<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>steps.rb</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~R</string>
	<key>name</key>
	<string>Ruby (Sinatra)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(get|put|post|delete|head|error|configure|before|helpers|use_in_file_template!)\b</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.ruby</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ruby.sinatra</string>
	<key>uuid</key>
	<string>1522587B-5E4F-45CE-AD11-5E2F44467EDC</string>
</dict>
</plist>
